#ifndef LIQUID_CRYSTAL_CUSTOM_INTERFACELENGTH_H
#define LIQUID_CRYSTAL_CUSTOM_INTERFACELENGTH_H

/**
 * Instruction bit name - DL
 */
enum InterfaceLength {
    FOUR_BIT = 0,
    EIGHT_BIT = 1,
};

#endif //LIQUID_CRYSTAL_CUSTOM_INTERFACELENGTH_H
